name: Deploy Database
on:
  push:
    branches:
      - main

permissions:
    id-token: write
    contents: read  

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: './'
          changeLogFile: 'changelog.sql'
          username: ${{ env.DATABASE_USERNAME }}
          password: ${{ env.PASSWORD }}
          url: jdbc:${{ env.DATABASE_URL }}
